# Generated by Django 5.0 on 2023-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки')),
                ('terminal_series', models.CharField(max_length=10, verbose_name='Серия терминала')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='Номер терминала')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='Номер терминала')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_series', models.CharField(max_length=10, unique=True, verbose_name='Серия терминала')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
